"""indexes

Revision ID: cee3509a7843
Revises: 1f768d1d7a6a
Create Date: 2021-08-14 12:43:39.322023

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cee3509a7843'
down_revision = '1f768d1d7a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    # ### end Alembic commands ###
