"""Modified User table

Revision ID: e0093654f311
Revises: 3bab954ff310
Create Date: 2021-08-08 02:43:08.030620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0093654f311'
down_revision = '3bab954ff310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
